### ISSUE TITLE
Decouple graphics + user input from game logic for testing - Find areas that require changes

### ISSUE THREAD

**Issue by jam-sut** [ENG1-TEAM3/project_eng1_team3_A2#1]
Go through code base and check for testability, list areas for changes.

**Comment by jam-sut** [comment]
Any code that contains references to graphics throws errors when tested with the headless environment (Need to test, other groups say they have had this problem). We need to go through the codebase and find ways to test methods and functionalities that normally require graphics.

User input can also cause issues when testing code, if methods directly contain keypress detection inside of them they are difficult to test. It would be good to rewrite these methods so that they can be tested without having to simulate keypresses in the testing code.

**Comment by jam-sut** [comment]
[https://docs.google.com/document/d/1lxlseZefOka-mmYLrDbVrwbOVfwFpE8m2u_5AdhhAEs/edit](url)
^ List the changes here

**Comment by jam-sut** [comment]
https://docs.google.com/document/d/1lxlseZefOka-mmYLrDbVrwbOVfwFpE8m2u_5AdhhAEs/edit
^ List the changes here

**Comment by jam-sut** [comment]
Looked over all code, only one main issue with the user input method in the cook class.

**Comment by CaiHughes** [comment]
Hi James,

I'm afraid I'm on Leave of Absence due to medical issues for the rest of
the year and therefore I am no longer a part of your group.

I'm very sorry,
Kindest regards,
Cai

**Comment by jam-sut** [comment]
Thanks for letting us know,
James
